# MCU name
MCU = RP2040

# Bootloader selection
BOOTLOADER = rp2040

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
ANALOG_DRIVER_REQUIRED = yes
# JOYSTICK_ENABLE = yes

I2C_DRIVER_REQUIRED = yes

OS_DETECTION_ENABLE = yes