# MCU name
MCU = RP2040

# Bootloader selection
BOOTLOADER = rp2040

COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
ANALOG_DRIVER_REQUIRED = yes
# JOYSTICK_ENABLE = yes
MOUSEKEY_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_DRIVER_ENABLE = yes
OLED_TRANSPORT = i2c
LTO_ENABLE = yes
I2C_DRIVER_REQUIRED = yes

OS_DETECTION_ENABLE = yes

CONSOLE_ENABLE = yes